/***********************************************************************/
/*  													               */
/*      PROJECT NAME :  FourAxisControl                                */
/*      FILE         :  FourAxisControl.c                              */
/*      DESCRIPTION  :  Main Program                                   */
/*      CPU SERIES   :  RX600                                          */
/*      CPU TYPE     :  RX62N                                          */
/*  													               */
/*      This file is generated by KPIT Eclipse.                        */
/*  													               */
/***********************************************************************/                                                                        
#include "Global.h"
extern void BlinkRunLED(void);
//extern void Init24C04(void);
extern void SetupTimer1Interrupt(void);

void main(void)
{
	OUTEN = 1;
	Enableb485Rx();	
    ServoInit();
	InitVariable();
	
	EncoderInit();
	SetupTimer1Interrupt();// 定时器方式
	//IOInterruptInit();// IO中断方式
	CalGearRatio();
	while(1)
	{
		ReadInput();
		Action();
		WriteOutput();
		CheckReceData();
		BlinkRunLED();
	}
}



